# Server configuration
server:
  shutdownGracePeriod: 120s
  requestLog:
    appenders: []
  adminConnectors:
  - type: http
    port: 43567
  applicationConnectors:
  - type: http
    port: 43568

database:
  minSize: 5
  driverClass: oracle.jdbc.OracleDriver
  maxSize: 20
  validationQuery: 'select 1 from dual'
  logValidationErrors: True
  url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=some_oracle_host.loc)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xedb)))
  initialSize: 5
  password: some_password
  user: some_user
  properties:
    hibernate.generate_statistics: False
    hibernate.jdbc.time_zone: Europe/Berlin

swagger:
  enabled: true
  resourcePackage: com.some.resource.package
  title: service-fancy-app
  schemes:
    - https
    - http


someGeoCoordinatedPois:
  boundary.lat: 41.37088
  boundary.lon: 2.183384
